# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # Enable session support
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # Configure CORS
    # cors:
    #     allow_origin: ['http://localhost:3000']
    #     allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    #     allow_headers: ['Content-Type', 'Authorization']
    #     max_age: 3600

    # Enable validator
    validation: { enable_attributes: true }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file